apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: cubbychat
spec:
  selector:
    app.kubernetes.io/name: cubbychat-frontend
  ports:
    - name: http
      port: 80
      targetPort: http
