package plan

import (
	"fmt"
	"strings"
)

// Render writes the plan as the text cub kubara plan prints.
func Render(p Plan) string {
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	source := "config only; Kubara has not generated it yet"
	if p.Generated {
		source = "generated by Kubara; chart versions read from what it wrote"
	}
	w("Kubara platform  %s  (%s)", p.Source, source)
	w("Catalogs         %s, %s", p.Bootstrap.OCI, p.General.OCI)
	w("")

	w("Stages, in the order a change rolls out")
	for i, st := range p.Stages {
		w("  %d. %s", i+1, st.Name)
		for _, cl := range st.Clusters {
			delivery := "runs Kubara's hub Argo CD"
			if cl.Type != "hub" {
				delivery = "delivered by " + p.Hub + "'s Argo CD, as Kubara wires it"
			}
			w("     %-22s %-5s  %s", cl.Name, cl.Type, delivery)
			w("     %-22s        runs %s", "", strings.Join(cl.Components, ", "))
		}
	}
	w("")

	w("Components: a base per component, a variant per cluster it runs on")
	for _, c := range p.Components {
		w("  %s  (%s)", c.Name, c.Catalog)
		w("    base      %s  reaches no cluster", c.Base)
		var clusters []string
		for _, v := range c.Variants {
			clusters = append(clusters, v.Cluster)
		}
		w("    variants  %s-<cluster> for %s", strings.TrimSuffix(c.Base, "-base"), strings.Join(clusters, ", "))
		if len(c.Upstream) == 0 {
			w("    chart     Kubara's own chart; no upstream chart to check")
		}
		for _, u := range c.Upstream {
			w("    chart     %s %s from %s", u.Chart.Name, u.Chart.Version, u.Chart.Repository)
			w("              %s", evidenceLine(u))
		}
	}
	w("")

	s := p.Summary()
	w("Workshop evidence  %d of %d upstream charts checked at the exact version Kubara pins; %d checked at another version; %d from another repository; %d not in the Workshop Catalog.",
		s.Checked, s.Charts, s.OtherVersion, s.OtherRepository, s.Unchecked)
	w("                   Kubara's catalogs stay the source of every component; evidence only annotates it. Workshop Catalog at %s.", short(p.Workshop.Commit))
	w("")

	w("ConfigHub would hold %d Spaces: a base Space per component, and a variant Space per cluster it runs on.", p.SpaceCount())
	w("  Each base holds what Kubara generated for the earliest-stage cluster that runs it, and a rollout workflow:")
	w("  the stages above in order, each waiting for the stage ahead, and an approval attestation")
	w("  (cub variant approve) before each release. Each variant records its cluster's own render as a change.")
	w("  Secret values stay out of ConfigHub: a Secret keeps its keys and loses its values.")
	w("  One more Space, %s-kubara-generated, keeps what Kubara generated for each base, so a new", p.Prefix)
	w("  catalog version reaches a base as one change you review.")
	w("  Kubara's hub, AppProject and ApplicationSets stay as Kubara generates them, and keep delivering")
	w("  from Git until handover, which points each ApplicationSet at the cluster's approved release instead.")
	w("")

	if len(p.Notes) > 0 {
		w("Notes")
		for _, n := range p.Notes {
			w("  - %s", n)
		}
		w("")
	}
	if len(p.Problems) > 0 {
		w("Fix these first")
		for _, pr := range p.Problems {
			w("  - %s", pr)
		}
		w("")
	}

	w("Next")
	if p.Generated {
		w("  cub kubara apply %s --out <dir>   # render each cluster and write apply.sh, the cub steps above", p.Source)
	} else {
		w("  kubara --work-dir %s --config-file config.yaml --env-file .env generate --helm", p.Source)
		w("  cub kubara plan %s   # again, with the versions Kubara wrote", p.Source)
	}
	w("")
	w("Offline: no account, no cluster, nothing changed.")
	return b.String()
}

func evidenceLine(u UpstreamPlan) string {
	e := u.Evidence
	switch e.Status {
	case "checked":
		var bases []string
		for _, b := range e.Chart.Bases {
			bases = append(bases, fmt.Sprintf("%s %s", b.Name, b.Verdict))
		}
		return fmt.Sprintf("Workshop checked this version (%s): %s", strings.Join(bases, "; "), e.Chart.Page)
	case "other-version":
		return fmt.Sprintf("Workshop checked %s, not %s", strings.Join(e.OtherVersions, ", "), u.Chart.Version)
	case "other-repository":
		return fmt.Sprintf("Workshop checked this version from %s, a different repository; not claimed", e.Chart.Repository)
	default:
		return "not in the Workshop Catalog"
	}
}

func short(commit string) string {
	if len(commit) > 9 {
		return commit[:9]
	}
	return commit
}
